### ISSUE TITLE
Token price abnormal

### ISSUE THREAD

**Issue by ZzikoWang** [balancer-labs/balancer-core#225]
Please help me, the token I put in cannot display the price.
  "name": "QuickCash",
  "website": "https://quickcash.com/",
  "short_description": "QuickCash stable currency system.",
  "explorer": "https://cn.etherscan.com/token/0xe74b35425fe7e33ea190b149805baf31139a8290" 

![balancerprice](https://user-images.githubusercontent.com/29268352/92319187-8cdfa500-f048-11ea-9fcf-b7abc38e19ac.jpg)

**Comment by mikemcdonald** [comment]
This repo is for the core smart contracts, closing
